######
POST http://localhost:4004/odata/v2/capital-assets-disposal/AssetDisposalMaster
Content-Type: application/json

{
    "RequestNo": "",
    "ProcessCode_code": "A",
    "DocumentStatus_code": "C",
    "WorkflowStatus_code": "X",
    "cada": {
        "CADANo": "",
        "RequestDate": "2026-06-29",
        "Plant": "Petrochemical Unit",
        "Department": "Information Technology",
        "RequestedBy": "EMP0432",
        "RequestedByName": "John Doe",
        "BuyBackApplicable": "true", 
        "CSRDistribution": "false",
        "ReasonForDisposal": "Asset life cycle ended.",
        "AlternativeUsesExplored": "None viable",
        "ModeOfDisposalRecommended": "Scrap Sale",
        "RepairTransferredTo": "",
        "TotalOriginalCost": 75000.00,
        "TotalWrittenDownValue": 5000.00
    }
}